apiVersion: secretgen.carvel.dev/v1beta1
kind: SecretImport
metadata:
  name: space-kubeconfig
  namespace: basic-helm
spec:
  fromNamespace: ucp-token-generator
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: space-store
  namespace: tpk8s-secrets-mgmt
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      authRef:
        name: space-kubeconfig
        key: value.yaml
      # server:
      #   caBundle: Cg==