---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  app1-secret
  namespace: tpk8s-secrets-mgmt
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: aws-sm-store
  target:
    name: app1-secret
  data:
    - secretKey: api_key
      remoteRef:
        key: tpk8s/space/app1
        property: api_key
    - secretKey: db_url
      remoteRef:
        key: tpk8s/space/app1
        property: db_url
---
# push to space

apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: app1-secret
  namespace: tpk8s-secrets-mgmt
spec:
  updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 2m # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: space-store
      kind: SecretStore
  selector:
    secret:
      name: app1-secret # Source Kubernetes secret to be pushed
