apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store
  namespace: ucp-token-generator
spec:
  provider:
    kubernetes:
      remoteNamespace: ucp-token-generator
      auth:
        serviceAccount:
          name: "token-generator"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt