---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: space-kubeconfig
  namespace: ucp-token-generator
spec:
  toNamespace: '*'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  space-kubeconfig
  namespace: ucp-token-generator
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: space-kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              server: https://ucp.platform.tanzu.broadcom.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/3b65ba5e-52a4-4666-ad29-4eefab93127b/space/helm-app-space
            name: space
          contexts:
          - context:
              cluster: space
              user: sa-tanzu-platform-user
            name: space
          current-context: space
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token

