---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: space-1
  namespace: amer-west
spec:
  force: false
  interval: 1m0s
  dependsOn:
  - name: amer-west
  path: ./templated-spaces/project/spaces/space-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: amer-west
  kubeConfig:
    secretRef:
      name: space-1-kubeconfig