apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Space
metadata:
  name: no-packaging-app-space
  namespace: default
spec:
  availabilityTargets:
  - name: warroyo-aks-v2
    replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      profiles:
      - name: apps.tanzu.vmware.com
        values:
          inline: null
      - name: deployments
        values:
          inline: null
      resources: {}
  updateStrategy:
    type: RollingUpdate