apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  empty
  namespace: amer-west
spec:
  target:
    name: space-1-kubeconfig
  dataFrom:
  - extract:
      key: space-1-info
  - extract:
      key: amer-west-project-info

