apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amer-west
namePrefix: space-1-
resources:
- ../../../../../base/kubeconfig


patches:
- path: kubeconfig-patch.yml
  target:
    kind: ExternalSecret
    name: kubeconfig