# expose the deployments and services capabilties
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: deployments.se.ext.tanzu.com
  namespace: default
spec:
  defaultNamespace: unusable-namespace
  packageRef:
    refName: deployments.se.ext.tanzu.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: pkg-installs-sa
