apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: fluxcd-helm-controller.tanzu.vmware.com
  namespace: default
spec:
  defaultNamespace: unusable-namespace
  packageRef:
    refName: fluxcd-helm-controller.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: pkg-installs-sa
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: fluxcd-source-controller.tanzu.vmware.com
  namespace: default
spec:
  defaultNamespace: unusable-namespace
  packageRef:
    refName: fluxcd-source-controller.tanzu.vmware.com
    versionSelection:
      constraints: '>0.0.0'
      prereleases: {}
  serviceAccountName: pkg-installs-sa
