apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeconfigs
  namespace: ucp-token-generator
spec:
  interval: 10m
  dependsOn:
  - name: external-secrets-crds
  targetNamespace: ucp-token-generator
  sourceRef:
    kind: GitRepository
    name:  ucp-token-generator
  path: ./common/kubeconfigs
  prune: true
  timeout: 1m