---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-generator
  namespace: ucp-token-generator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-generator
  namespace: ucp-token-generator
subjects:
- kind: ServiceAccount
  name: token-generator
  namespace: ucp-token-generator
roleRef:
  kind: Role
  name: token-generator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-generator
  namespace: ucp-token-generator