apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amer-west
resources:
- secretsetup.yml
- flux-kustomization.yml
- ../spaces/space-1/setup
- ../spaces/space-2/setup
- project-secret.yml
- ./kubeconfig
