
## this file pulls in the secret for the access token thats needed to generate
## kubeconfigs, creates a local secret store that external secrets can use, and the SA and role needed to access it.
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: ucp-access-token
  namespace: amer-west
spec:
  fromNamespace: ucp-token-generator
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store
  namespace: amer-west
spec:
  provider:
    kubernetes:
      remoteNamespace: amer-west
      auth:
        serviceAccount:
          name: "secretstore"
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretstore
  namespace: amer-west
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretstore
  namespace: amer-west
subjects:
- kind: ServiceAccount
  name: secretstore
  namespace: amer-west
roleRef:
  kind: Role
  name: secretstore
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretstore
  namespace: amer-west