apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amer-west
namePrefix: amer-west-
resources:
- ../../../base/kubeconfig


patches:
- path: kubeconfig-patch.yml
  target:
    kind: ExternalSecret