apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample2
  namespace: default
  labels:
    app: python-sample2
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
     app: python-sample2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: main
      labels:
        app: python-sample2
    spec:
      automountServiceAccountToken: false
      containers:
      - image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/python-sample@sha256:3860285440297e3fa086acb33a1df1eeca9a3c26aad932af049e26db5033ccfe
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 5000
          name: main
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 300