---
apiVersion: v1
kind: Service
metadata:
  name: python-sample2
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-sample2
  sessionAffinity: None
  type: ClusterIP