apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample2
  namespace: default
  labels:
    app: python-sample2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
     app: python-sample2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: main
      labels:
        app: python-sample2
    spec:
      automountServiceAccountToken: false
      containers:
      - image: us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/python-sample@sha256:3860285440297e3fa086acb33a1df1eeca9a3c26aad932af049e26db5033ccfe
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 5000
          name: main
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 300
     

---
apiVersion: v1
kind: Service
metadata:
  name: python-sample2
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-sample2
  sessionAffinity: None
  type: ClusterIP
# ---
# apiVersion: apps.tanzu.vmware.com/v1
# kind: ContainerApp
# metadata:
#   name: python-sample2
#   labels:

#   annotations:
#     containerapp.apps.tanzu.vmware.com/class: "kubernetes"
# spec:
#   description: python2 app
#   contact:
#     slack: "#my-helm-apps"
#   image:  us-west1-docker.pkg.dev/fe-cpage/west-sa-build-registry/warroyo/python-sample@sha256:3860285440297e3fa086acb33a1df1eeca9a3c26aad932af049e26db5033ccfe
#   replicas: 1
#   relatedRefs:
#     - for: kubernetes.list-replicas
#       kind: Pod
#       labelSelector: app=python-sample2
#     - for: kubernetes.scale-replicas
#       kind: Deployment
#       name: python-sample2
#       keyPath: .spec.replicas
#     - for: kubernetes.delete
#       kind: Deployment
#       apiGroup: apps
#       name: python-sample2
#     - for: kubernetes.delete
#       kind: Service
#       name: python-sample2