---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name:  kubeconfig
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: k8s-store
  target:
    name: kubeconfig
    template:
      engineVersion: v2
      data:
        value.yaml: |
          apiVersion: v1
          clusters:
          - cluster:
              {{- if and (index . "project") (index . "space") }}
              server: https://ucp.platform.tanzu.broadcom.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/{{ .project }}/space/{{ .space }}
              {{- else if and (index . "project") (index . "clustergroup") }}
              server: https://ucp.platform.tanzu.broadcom.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/{{ .project }}/clustergroup/{{ .clustergroup }}
              {{- else if (index . "project") }}
              server: https://ucp.platform.tanzu.broadcom.com/org/77aee83b-308f-4c8e-b9c4-3f7a6f19ba75/project/{{ .project }}
              {{- end}}
            name: default
          contexts:
          - context:
              cluster: default
              user: sa-tanzu-platform-user
            name: default
          current-context: default
          kind: Config
          preferences: {}
          users:
          - name: sa-tanzu-platform-user
            user:
              token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: ucp-access-token
      property: access_token
  dataFrom:
  - extract:
      key: replaceme


