apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/space


patches:
- target:
    kind: Space
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: space-2